config/routes.rb
LoginDemo::Application.routes.draw do
  
  resources :medias do
    get 'process_document'
    collection do
    get 'delivery_report'
    end
  end
  
  resources :events do
    get 'send_invites'
  end
  
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup
  
  match 'unauthorized_access' => 'users#unauthorized', :as => :unauthorized_access

  root :to => 'user_sessions#new'
  

end

app/models/media.rb
require "date"
require 'open-uri'
class Media < ActiveRecord::Base
		attr_accessible :document
		
		# Attachment handler : Paperclip
		has_attached_file :document
		validates_attachment :document, content_type: { content_type: "application/pdf" }
		validates :document_file_name, uniqueness: true, presence: true
		
		# Associations
		belongs_to :user
		
		def error_message(field_name)
				h = {:document_file_name => "Select any file.", :document_content_type => "Select any PDF file."}
				h[field_name]
		end
		
		def extract_events
				io     = open(full_url)
				reader = PDF::Reader.new(io)
				
				reader.pages.each do |page|
						extract_each_page(page.text)
				end
				
				mark_as_processed
		end
		
		def mark_as_processed
				self.is_processed = true
				self.save
		end
		
		def full_url
				(Rails.env == "development") ? "http://localhost:3000#{self.document.url}".split("?")[0] : ""
		end
		
		def extract_each_page(page_content)
				events = []
				page_content.gsub("\n\n","\n").gsub(/\n\s+/,"").split("\n").each do |d|
						if d.split(" ").length > 4
								events << d
						end
				end

				months = %w(january february march april may june july august september october november december)
				@month = ""
				events.each_with_index do |e, i|
						if i == 0
								months.each do |m|
										@month = m if e.downcase.include?(m)
								end
								@year = e.split(@month.capitalize)[1].split("Slno")[0].to_i
						else
								d = DateTime.new(@year,(months.index(@month)+1),e.split(" ")[1].to_i)
								Event.create(:title => "#{@month}-#{@year}-events", :description => e, :start_date => d, :end_date => d)
						end
				end
		end
end

app/controllers/medias_controller.rb
class MediasController < ApplicationController
		before_filter :media_processed, :only => :process_document
		def index
				@medias = Media.all
		end
		
		def new
				@media = Media.new
		end
		
		def create
				@media = Media.create(params[:media])
				if @media.save
						redirect_to medias_path
				else
						render :new
				end
		end
		
		def edit
		end
		
		def update
		end
		
		def destroy
		end
		
		def process_document
				@media.extract_events
				redirect_to medias_path
		end
		
		def delivery_report
				@users = User.where("role != 'admin'")
				render :layout => false
		end
		
		private
		def media_processed
				if Media.exists?(params[:media_id])
						@media = Media.find(params[:media_id])
						return redirect_to medias_path if @media.is_processed
				else
						return redirect_to medias_path
				end
		end
end

app/helpers/medias_helper.rb
module MediasHelper
end

app/views/medias/delivery_report.html.erb
<div class="message_report">
		<% @users.each do |u| %>
				<span class="report_info"><%= u.login.titleize %>: Message sent. <br />
				</span>
		<% end %>
</div>

app/views/medias/index.html.erb
<% if current_user.admin? %>
		<div>
				<%= link_to "Upload Event", new_media_path %>
		</div>
<% end %>

		<div id="sidebar" style="float: left;width: 500px;">
		<ul>
		<li>
		<h2>File List</h2>
		<ul>
				<% if @medias.empty? %>
						No Events available to display.
				<% else %>						
						<table width="100%" border="1">
								<tr class="header">
										<td width="70%">Title</td><td width="30%">Actions</td>
								</tr>
								<% @medias.each do |media| %>
										<tr>
												<td><%= media.document_file_name %></td>
												<td>
														<% if media.is_processed %>
																Already processed.
																<%#= link_to "Report", delivery_report_medias_path, :class => "ajax", :title => "Delivery Report", :style => "color: #AE4D5A;" %>
														<% else %>
																<%= link_to "Process", media_process_document_path(media), :style => "color: #AE4D5A;" %>
														<% end %>
												</td>
										</tr>
								<% end %>
						</table>
				<% end %>
		</ul>
		</li>
		</ul>
		</div>	

app/views/medias/new.html.erb
<h2>Upload Event</h2>

<% @media.errors && @media.errors.messages.each_pair do|field,msg| %>
		<div class="errors">
				<%= @media.error_message(field) %>
		</div>
<% end %>
<%= simple_form_for @media, :url => medias_path, :html => { :class => 'form-horizontal' } do |f| %>
		<%= f.file_field :document %>
		<div class="form-actions">
				<%= f.button :submit, :value => "Upload" %>
		</div>
<% end %>
  