config/routes.rb
LoginDemo::Application.routes.draw do
  
  resources :medias do
    get 'process_document'
    collection do
    get 'delivery_report'
    end
  end
  
  resources :events do
    get 'send_invites'
  end
  
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup
  
  match 'unauthorized_access' => 'users#unauthorized', :as => :unauthorized_access

  root :to => 'user_sessions#new'
  

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :crypted_password, :login, :password_salt, :persistence_token, :password, :password_confirmation, :email, :register_number, :mobile_number, :role
  ROLES = %w(student staff)
  
  # Authentication
  acts_as_authentic
  
  # Validations
  validates :register_number, presence: true, if: Proc.new { |user| user.student? }
  validates :mobile_number, presence: true
  validates :role, presence: true
  
  # Associations
  has_many :medias
  
  def admin?
    role == "admin"
  end
  
  def student?
    role == "student"
  end
  
  def staff?
    role == "staff"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
		before_filter :require_user, :only => [:edit, :show, :update]
		before_filter :require_no_user, :only => [:new, :create]
  before_filter :block_admin_creation, :only => [:create]
  layout "before_login", :only => [:new, :create]
  
  # Cancan check role and authorize user based
  load_and_authorize_resource
  skip_load_and_authorize_resource :only => [:new, :create]
		
		def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    # Saving without session maintenance to skip
    # auto-login which can't happen here because
    # the User has not yet been activated
    if @user.save
      flash[:notice] = "Your account has been created."
      redirect_to signup_url
    else
      flash[:notice] = "There was a problem creating you."
      render :action => :new
    end

  end

  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user # makes our views "cleaner" and more consistent
    if @user.update_attributes(params[:user])
      flash[:notice] = "Account updated!"
      redirect_to account_url
    else
      render :action => :edit
    end
  end
  
  def unauthorized
  end
  
  def block_admin_creation
    if params[:user] && params[:user][:role].downcase == "admin"
      params[:user][:role] = "student"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form.input :login, label: '<abbr title="required">*</abbr> Login: '.html_safe %>
<%= form.input :email, label: '<abbr title="required">*</abbr> Email Address: '.html_safe %>
<%= form.input :password, label: '<abbr title="required">*</abbr> Password: '.html_safe %>
<%= form.input :password_confirmation, label: '<abbr title="required">*</abbr> Password Confirmation: '.html_safe %>
<%= form.input :mobile_number, label: 'Mobile Number: ' %>

<% if params[:action] == "new" || params[:action] == "create" %>
		<div class="control-group">
				<label for="user_role" class="string required control-label"><abbr title="required">*</abbr> Role:</label>
				<div class="controls">
						<%= form.collection_select :role, User::ROLES, :to_s, :humanize %>
				</div>
		</div>
<% end %>

<%= form.input :register_number, label: 'Register Number: ' %>

app/views/users/edit.html.erb
<h2>Edit Account</h2>

<%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
		<%= render :partial => "form", :object => f, :locals => { :user => @user } %>
		<div class="form-actions">
				<%= f.button :submit, :value => "Update" %>
		</div>
<% end %>

app/views/users/new.html.erb
<div id="loginContainer">

		<h2>Register</h2>

		<%= simple_form_for @user, :html => { :class => 'form-horizontal' } do |f| %>
				<%= render :partial => "form", :object => f, :locals => { :user => @user } %>
				<div class="form-actions">
						<%= f.button :submit, :value => "Register" %>
				</div>
		<% end %>
  
		<div>If you already have account with us, try login</div>
		<%= link_to "Login", root_path %>
		
</div>

app/views/users/show.html.erb
<h2>View Account</h2>

<p>
<b>Login:</b>
<%=h @user.login %>
</p>
<p>
<b>Email:</b>
<%=h @user.email %>
</p>
<% if @user.student? %>
		<p>
				<b>Register Number:</b>
				<%=h @user.register_number %>
		</p>
<% end %>
<p>
<b>Mobile Number:</b>
<%=h @user.mobile_number %>
</p>


<%= link_to 'Edit Account', edit_account_path %>

app/views/users/unauthorized.html.erb
<h2>
		You are not authorized to do this action.
</h2>