config/routes.rb
LoginDemo::Application.routes.draw do
  
  resources :medias do
    get 'process_document'
    collection do
    get 'delivery_report'
    end
  end
  
  resources :events do
    get 'send_invites'
  end
  
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup
  
  match 'unauthorized_access' => 'users#unauthorized', :as => :unauthorized_access

  root :to => 'user_sessions#new'
  

end

app/views/shared/_error_messages.html.erb
<% if target.errors.any? %>
		<div id="errorExplanation">
				<h4><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h4>
				<ul>
						<% target.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
						<% end %>
				</ul>
		</div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer">
	<p>Copyright (c) 2013 iReminder.com. All rights reserved.</p>
</div>

app/views/shared/_header.html.erb
<div id="header-wrapper">
		<div id="header">
				<div id="menu1">
						<ul>
								<% if current_user %>
										<li class="<%= ((params[:controller] == 'users') && (%w(show update edit).include?(params[:action]))) ? 'current_page_item' : '' %>"><%= link_to "My Account", account_path %></li>
										<li class="<%= (params[:controller] == 'events') ? 'current_page_item' : '' %>"><%= link_to "Events", events_path %></li>
								<% end %>
						</ul>
				</div>
				<div id="logo">
						<h1><%= link_to "iReminder", root_path %></h1>
						<p>An Intelligent Reminder System</p>
				</div>
				<div id="menu2">
						<ul>
								<% if current_user %>
										<li style="margin-top: 13px; width: 200px;"><span id="displayUserName">Welcome <%= current_user.login %> | <%= current_user.role.titleize %></span></li>
										<li><%= link_to "Logout", logout_path, :method => :delete %></li>
								<% end %>
						</ul>
				</div>
		</div>
</div>
	