config/routes.rb
LoginDemo::Application.routes.draw do
  
  resources :medias do
    get 'process_document'
    collection do
    get 'delivery_report'
    end
  end
  
  resources :events do
    get 'send_invites'
  end
  
  resources :user_sessions

  match 'login' => "user_sessions#new",      :as => :login
  match 'logout' => "user_sessions#destroy", :as => :logout

  resources :users  # give us our some normal resource routes for users
  resource :user, :as => 'account'  # a convenience route

  match 'signup' => 'users#new', :as => :signup
  
  match 'unauthorized_access' => 'users#unauthorized', :as => :unauthorized_access

  root :to => 'user_sessions#new'
  

end

app/models/event.rb
class Event < ActiveRecord::Base
		attr_accessible :start_date, :end_date, :title, :description

		# Validations
		validates :title, presence: true
		validates :description, presence: true, uniqueness: true
		validates :start_date, presence: true
		validates :end_date, presence: true
		
		validate :start_should_be_lower
		
		def start_should_be_lower
				errors.add(:start_date, "Start date should be less than End date.") if self.start_date > self.end_date
		end
		
		def send_reminder_to_all
				error = false
				begin
						tm = TwilioManager.new
						users = User.where("role != 'admin'")
						users.each do |user|
								tm.send_sms(user.mobile_number, self.description)
								#~ puts "sending sms to #{user.mobile_number}. Content: #{self.description}"
						end
				rescue
						error = true
						puts "#{$!.inspect}"
				end
				
				if !error
						update_reminder_sent_status
				end
		end
		
		def update_reminder_sent_status
				self.is_invited = true
				self.save
		end
		
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
		load_and_authorize_resource
		
		before_filter :already_invited, :only => [:send_invites]
		def index
				@events = Event.all
		end
		
		def new
				@event = Event.new
		end
		
		def create
				@event = Event.create(params[:event])
				if @event.save
						redirect_to events_path
				else
						render 'new'
				end
		end
		
		def show
				@event = Event.find(params[:id])
		end
		
		def edit
				@event = Event.find(params[:id])
		end
		
		def update
				@event = Event.find(params[:id])
				if @event.update_attributes(params[:event])
						redirect_to events_path
				else
						render 'edit'
				end
		end
		
		def destroy
				@event = Event.find(params[:id])
				@event.delete
				redirect_to events_path
		end
		
		def send_invites
				@event.send_reminder_to_all
				redirect_to events_path
		end
		
		private
		def already_invited
				if Event.exists?(params[:event_id])
						@event = Event.find(params[:event_id])
						return redirect_to events_path if @event.is_invited?
				else
						return redirect_to events_path
				end
		end
		
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form.input :title, label: 'Title: '.html_safe %>
<%= form.input :start_date, label: 'Start Date: '.html_safe, class: "datepicker" %>
<%= form.input :end_date, label: 'End Date: '.html_safe, class: "datepicker" %>
<%= form.input :description, label: 'Description: '.html_safe, as: :text, :input_html => {:rows => 5, :cols => 30} %>

app/views/events/edit.html.erb
<h2>Edit Event</h2>

<%= simple_form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
		<%= render :partial => "form", :object => f, :locals => { :event => @event } %>
		<div class="form-actions">
				<%= f.button :submit, :value => "Update" %>
		</div>
<% end %>
  

app/views/events/index.html.erb
<% if current_user.admin? %>
		<div>
				<%= link_to "Add New Event", new_event_path %> | 
				<%= link_to "Upload Event", new_media_path %> | 
				<%= link_to "Upload List", medias_path %>
		</div>
<% end %>

		<div id="sidebar" style="float: left;width: 700px;">
		<ul>
		<li>
		<h2>Events List</h2>
		<ul>
				<% if @events.empty? %>
						No Events available to display.
				<% else %>						
						<table width="100%" border="1">
								<tr class="header">
										<td width="25%">Title</td><td width="50%">Description</td>
										<% if current_user.admin? %>
												<td width="25%">Actions</td>
										<% end %>
								</tr>
								<% @events.each do |event| %>
										<tr>
												<td><%= link_to event.title, event_path(event), :class => "titleLink" %></td>
												<td><%= event.description %></td>
												<% if current_user.admin? %>
														<td>
																<%= link_to "Edit", edit_event_path(event) %> | <%= link_to "Delete", event_path(event), :method => :delete, :confirm => "Are you sure want to delete Event?" %> |
																<% if event.is_invited? %>
																		Already Invited.
																		<%= link_to "Report", delivery_report_medias_path, :class => "ajax", :title => "Delivery Report", :style => "color: #AE4D5A;" %>
																<% else %>
																		<%= link_to "Send Reminder", event_send_invites_path(event) %>
																<% end %>
														</td>
												<% end %>
										</tr>	
								<% end %>
						</table>
				<% end %>
		</ul>
		</li>
		</ul>
		</div>	

app/views/events/new.html.erb
<h2>Create Event</h2>

<%= simple_form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
		<%= render :partial => "form", :object => f, :locals => { :event => @event } %>
		<div class="form-actions">
				<%= f.button :submit, :value => "Create" %>
		</div>
<% end %>
  

app/views/events/show.html.erb
<h4>View Event</h4>

<div id="content">
		<div class="post">
				<h2 class="title"><%= @event.title %></h2>
				<div class="entry">
						<p><%= @event.description %></p>
						<p>Starts at: <%= time_display @event.start_date %></p>
						<p>Ends at: <%= time_display @event.end_date %></p>
				</div>
		</div>
</div>